// src/app/layout.tsx
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dev-Team Project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-gray-100">
        <header className="bg-white shadow-md p-4 text-center">
          <h1 className="text-3xl font-bold">Dev-Team Project</h1>
        </header>
        <main className="container mx-auto p-4 mt-8">
          {children}
        </main>
        <footer className="bg-white shadow-md p-4 text-center absolute bottom-0 w-full">
          <p>&copy; 2026 Dev-Team. All rights reserved.</p>
        </footer>
      </body>
    </html>
  )
}
