import React from 'react';
import Head from 'next/head';
import HeroSection from '../components/HeroSection';

const HomePage: React.FC = () => (
  <div>
    <Head>
      <title>Home Page</title>
      <meta name="description" content="Welcome to our home page with a hero section." />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <HeroSection
      title="Welcome to Our Website"
      description="Discover the best of our products and services."
      imageUrl="/hero-background.jpg"
    />
  </div>
);

export default HomePage;
import Head from 'next/head';
import HeroSection from '@/components/HeroSection';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='min-h-screen'>
                <HeroSection
                    title='Welcome to Our Platform'
                    description='Discover the latest in cutting-edge technology and innovation.'
                    buttonText='Get Started'
                    buttonLink='/getting-started'
                />
            </main>
        </>
    );
}
